### ISSUE TITLE
map.json vs main.json mixed up in branches

### ISSUE THREAD

**Issue by koileLab** [simondueckert/sendezentrum#2]
In dem main branch heißt die Hauptkarte **main.json** im gh-pages heißt sie **map.json** 
`https://c0c0bird.github.io/chaos-world/main.json` verweist auf `raw.githubusercontent.com\/simondueckert\/sendezentrum\/gh-pages\/map.json` Im Showroom ist als exitUrl **main.json** angeben, deshalb gibt's nen 404, wenn du über die Chaos Welt in das Sendezentrum gehst, hoch in den Showroom und dann wieder runter ins Sendezentrum willst...

**Comment by shiller79** [comment]
Danke für die Info. Der Verweis auf gh-pages ist richtig. Habe den exitUrl in der showroom.json entsprechend angepasst.
